# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!dist/**"
    - "!build/**"
    - "!bin/**"
    - "!pnpm-lock.yaml"
    - "!**/*.generated.*"
  path_instructions:
    - path: "src/bridge.ts"
      instructions: "Review for MCP bridge stability: subprocess lifecycle, error recovery, singleton pattern correctness."
    - path: "src/hooks/**"
      instructions: "Review for plugin hook safety: no console output (logs to file only), graceful error handling, budget management."

chat:
  auto_reply: true
